### ISSUE TITLE
list of cards showing past trips 

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#1]
## Value Preposition

**As a User** 
**I need** to see a list of past trips 
**to be able to** return to the memories and impressions

## Description

![list-of -cards](https://user-images.githubusercontent.com/78484916/159584919-fda9b26d-92e2-49e4-beb9-9940028a6d83.png)

## Acceptance Criteria

- [ ] Each card is displayed with a placeholder picture and text - no responsive data yet
- [ ] The list is scrollable 
- [ ] The list contains a main title 
- [ ] Each card shows a picture of the respective country 
- [ ] Each card shows the respective country and city name

## Tasks

- [ ] Create feature branch `card-list`
- [ ] Create card component with storybook
- [ ] Write specs for card component 
- [ ] Add card component to app
- [ ] Add styles
- [ ] Test on mobile device / different browser
