### ISSUE TITLE
delete confirmation 

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#13]
## Value Preposition

**As a User** 
**I need** to see a confirm message before finally deleting an entry
**to be able to** cancel the process if I changed my mind or accidentally clicked on the delete button

## Description

![modal-delete-confirmation](https://user-images.githubusercontent.com/78484916/161434441-6bbea96b-6d31-4551-8e98-40a81f47eab5.png)

## Acceptance Criteria

- [x] Confirm message will appear by clicking the Delete-Button
- [x] Card will only be deleted if "YES" is clicked

## Tasks

- [x] Create feature branch `confirm-message`
- [x] Update Card Components
- [x] Update specs 
- [x] Update Storybook
- [x] Add styles
- [x] Test on mobile device / different browser
