### ISSUE TITLE
done confirmation to finish trips

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#14]
## Value Preposition

**As a User** 
**I need** to finish my trip after returning home
**to be able to** see it in my history of past trips

## Description

![modal-done-confirmation](https://user-images.githubusercontent.com/78484916/161437402-9fc5ecf9-2d9d-425b-a260-7112b15a7ea5.png)
 
## Acceptance Criteria

- [x] Confirm message will appear by clicking the "Done-Button"
- [x] If "YES" is clicked the trip will be shown on the past trip list
- [x] If "NO" is clicked the trip will remain on the future trip list

## Tasks

- [x] create feature branch `finish-trip`
- [x] Add "Done-Button" to card component
- [x] Create alert message
- [x] Update specs
- [x] Update Storybook
- [x] Add styles
- [x] Test on mobile device / different browser
