### ISSUE TITLE
edit card information

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#15]
## Value Preposition

**As a User** 
**I need** to edit my card information
**to be able to** correct mistakes or add information

## Description

![edit-card-information](https://user-images.githubusercontent.com/78484916/161507350-7f3951c6-6ab0-4dfe-a737-bc6de5e09848.png)

## Acceptance Criteria

- [x] Each card contains an "Edit-Button" 
- [x] On click on the "Edit Button" the user is presented with the form to change the respective information 
- [x] On submit, the edited card replaces the old card

## Tasks

- [x] Create feature branch `edit`
- [x] Create "Edit Button" as icon
- [x] Update form and card component
- [x] Write specs for edit logic
- [x] Update Storybook
- [x] Add the edited card to the future trip list and replace the old one
- [x] Add styles
- [x] Test on mobile device / different browser
