### ISSUE TITLE
refactoring

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#17]
## Value Preposition

**As a Developer** 
**I need** to refactor the existing code
**to be able to** keep the components cleaner and prevent repetitions

## Description

Refactoring the existing code without changing its external behavior to solve code-quality issues. 

## Tasks

- [ ] Create feature branch `refactoring`
- [ ] Refactoring all possible components 
- [ ] Update tests and storybook
- [ ] Test on mobile device / different browser
