### ISSUE TITLE
add new trips 

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#2]
## Value Preposition

**As a User** 
**I need** to add future trips
**to be able to** get an overview and to be able to plan 

## Description

![input-add-new-trip](https://user-images.githubusercontent.com/78484916/159664209-0cd5a729-90bb-4b94-86e1-74b6907d100f.png)

## Acceptance Criteria

- [ ] Two input fields to enter the destination and the date
- [ ] The input field "Enter destination" is required
- [ ] "Enter destination" has a max length of 50
- [ ] "Enter date" has a date format
- [ ] All whitespaces in inputs are trimmed on submit
- [ ] Button - on submit, a new trip is created 
- [ ] 

## Tasks

- [ ] Create feature branch "form"
- [ ] Create Form component 
- [ ] Create Form component with storybook
- [ ] Write specs for Form component 
- [ ] If "Enter destination" is empty, don´t send 
- [ ] Create Button component
- [ ] Create Form component with storybook
- [ ] Write specs for Button component
- [ ] Update App
- [ ] On submit the form inputs are saved 
- [ ] Add styles
- [ ] Test on mobile device / different browser
