### ISSUE TITLE
add photo upload

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#22]
## Value Preposition

**As a User** 
**I need** to be able to upload and display photos
**to be able to** save memories of my trips

## Description

![photo-upload](https://user-images.githubusercontent.com/78484916/162613365-929cc768-a5c8-44d4-bd53-474c87526324.png)

## Acceptance Criteria

- [x] There´s an "Upload photos" button which opens the photo upload on click
- [x] On submit photos are uploaded and displayed on the respective entry card
- [x] Photos are formatted to a specific size

## Tasks

- [x] Create feature branch `photo-upload`
- [x] Update PastTripForm component
- [x] Update Storybook
- [x] Update specs
- [x] Add styles 
- [x] Test on mobile device / different browser
