### ISSUE TITLE
edit notes content

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#25]
## Value Preposition

**As a User** 
**I need** to edit my note content
**to be able to** correct mistakes or add information

## Description

![edit-notes](https://user-images.githubusercontent.com/78484916/162900380-717a28fe-c7c2-432e-b7ef-eb3473a003e9.png)

## Acceptance Criteria

- [x] Each note entry contains an "Edit-Button"
- [x] On click on the "Edit Button" the user is presented with the form to change the respective information
- [x] On submit, the edited note replaces the old note entry

## Tasks

- [x] Create feature branch `edit-notes`
- [x] Add "edit-Button" to notes 
- [x] Update form and note component
- [x] Write specs for edit logic
- [x] Update Storybook
- [x] Add styles
- [x] Test on mobile device / different browser
