### ISSUE TITLE
add map

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#28]
## Value Preposition

**As a User** 
**I need** to see a map
**to be able to** add markers to the places I have already been

## Description

![map](https://user-images.githubusercontent.com/78484916/163034163-27f4471e-257c-448f-bf85-0328e15613fe.png)

## Acceptance Criteria

- [x] A new page is rendered which shows the map
- [x] Markers can be set to several places

## Tasks

- [x] Create feature branch `map`
- [x] Create map component
- [x] Update navigation to create a new page
- [x] Update App
- [x] Update Storybook
- [x] Update specs
- [x] Add styles
- [x] Test on mobile device / different browser
