### ISSUE TITLE
list of cards showing past trips 

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#3]
## Value Preposition

**As a User** 
**I need** to see a list of past trips 
**to be able to** return to the memories and impressions

## Description

![stories-of-past-trips](https://user-images.githubusercontent.com/78484916/159779979-0f4d4d96-8530-4eaf-b8f1-b2d77f89105b.png)

## Acceptance Criteria

- [ ] The list is scrollable and responsive

## Tasks

- [ ] Create feature branch `story-list`
- [ ] Create StoryList component with storybook
- [ ] Write specs for StoryList component 
- [ ] Map over array with static data for story-list
- [ ] Update App
- [ ] Add styles
- [ ] Test on mobile device / different browser
