### ISSUE TITLE
implement back-end

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#30]
## Value Preposition

**As a User** 
**I need** to save my data properly
**to be able to** access it at any time and different devices

## Description

Implement back-end to store trips, markers and photos

## Acceptance Criteria

- [ ] Trip, markers and photos are stored in a database 
- [ ] Data is available on different devices

## Tasks

- [ ] Create feature branch `backend`
- [ ] Implement MongoDB
- [ ] Implement mongoose
- [ ] Test on mobile device / different browser
