### ISSUE TITLE
list of cards showing past trips

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#4]
## Value Preposition

**As a User** 
**I need** to see a list of past trips 
**to be able to** return to the memories and impressions

## Description

![stories-of-past-trips](https://user-images.githubusercontent.com/78484916/159779979-0f4d4d96-8530-4eaf-b8f1-b2d77f89105b.png)

## Acceptance Criteria

- [x] The list is scrollable and responsive

## Tasks

- [x] Create feature branch `past-trip-list`
- [x] Create PastTripList component with storybook
- [x] Write specs for PastTripList component 
- [x] Map over array with static data for story-list
- [x] Update App
- [x] Add styles
- [x] Test on mobile device / different browser
