### ISSUE TITLE
form to enter notes to past trips

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#5]
## Value Preposition

**As a User** 
**I need** to enter notes to the past trips
**to be able to** remember favorite things experienced 

## Description

![stories-of-past-trips-and-enter-notes](https://user-images.githubusercontent.com/78484916/159782176-f9a22b9a-d9f7-42bb-959f-e85b8f03e5c1.png)

## Acceptance Criteria

- [x] On click on "Notes Button"- change from PastTripList page to PastTripNotes page
- [x] There should be a form with a label and an  input
- [x] Input field "Enter notes" has a max length of 500
- [x] All whitespaces in input are trimmed on submit
- [x] On submit on "Add Button", a new note is created  
- [x] If input field is empty, it doesn´t send on submit 
- [x] List of notes is scrollable
- [x] Text wraps inside Cards

## Tasks

- [x] Create feature branch `past-trip-notes`
- [x] Create PastTripNotes component
- [x] Create storybook component for PastTripNotes
- [x] Write specs for PastTripNotes component
- [x] Create Button component
- [x] Create storybook component for "Notes Button" and "Add Button"
- [x] Write specs for Button component 
- [x] Add Button to PastTripList component 
- [x] Add Button to PastTripList  component
- [x] Update App with conditional rendering for PastTripList  and PastTripNotes
- [x] Add styles
- [x] Test on mobile device / different browser
