### ISSUE TITLE
add delete button to story notes list

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#6]
## Value Preposition

**As a User** 
**I need** to delete existing notes
**to be able to** remove unnecessary notes or change notes

## Description

![delete-story-notes](https://user-images.githubusercontent.com/78484916/159787246-170cc0a6-4dbe-418f-bed7-da0cfdbb4a3a.png)

## Acceptance Criteria

- [x] On click on the "Delete Button", the note is removed

## Tasks

- [x] Create feature branch `delete-story-note`
- [x] Add "Delete Button" to storybook component "Button"
- [x] Add delete logic to PastTripNotes component
- [x] Update specs for PastTripNotes component 
- [x] Add styles
- [x] Test on mobile device / different browser
