### ISSUE TITLE
form to add a new trip

### ISSUE THREAD

**Issue by HannaSophia-92** [HannaSophia-92/capstone-project#7]
## Value Preposition

**As a User** 
**I need** to add upcoming trips
**to be able to** get an overview and plan the trip

## Description

![form-add-ew-trip](https://user-images.githubusercontent.com/78484916/160004530-d2f6d131-5c2a-45ad-ae6c-2a1922ff835d.png)

## Acceptance Criteria

- [x] Implement navigation 
- [x] The input field "Enter destination" is required
- [x] If "Enter destination" is empty, don´t send form on submit
- [x] "Enter destination" has a max length of 100
- [x] "Enter date" has a date format
- [x] All whitespaces in inputs are trimmed on submit
- [x] On submit, a new trip is created underneath the form
- [x] On click on the "Delete Button", the card is removed

## Tasks

- [x] Create feature branch "form-new-trip"
- [x] Create NewTripList component 
- [x] Add storybook
- [x] Write specs 
- [x] Implement react router to navigate to list of new trips
- [x] Add delete button and logic to NewTripList
- [x] Add styles
- [x] Test on mobile device / different browser
